# Generated by Django 2.1.7 on 2019-06-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(db_column='url_id', primary_key=True, serialize=False)),
                ('short_url', models.SlugField(db_column='short_url')),
                ('title', models.CharField(db_column='title', default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
