# Generated by Django 2.1.7 on 2019-06-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharework_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='long_url',
            field=models.URLField(db_column='long_url', default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urls',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_column='modified'),
        ),
    ]
