# Generated by Django 2.1.7 on 2019-06-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharework_api', '0002_auto_20190616_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.SlugField(db_column='short_url', max_length=7, unique=True),
        ),
    ]
